### ISSUE TITLE
Webcam source is not working

### ISSUE THREAD

**Issue by aloksingh17** [akshaybahadur21/GymLytics#1]
Tried with ```python3 GymLytics.py --type pushup --source 0``` but its not working for webcam. Is there something I am missing?

**Comment by aloksingh17** [comment]
<img width="528" alt="Screenshot 2023-09-04 at 10 26 39 AM" src="https://github.com/akshaybahadur21/GymLytics/assets/14039349/4c446598-ef21-45ce-9b3e-c1144fffbf73">

**Comment by akshaybahadur21** [comment]
@aloksingh17 can you set it to 1
`python3 GymLytics.py --type pushup --source 1`
